// <auto-generated />
using System;
using HwSync.Persistence.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HwSync.Persistence.Sqlite.Migrations.Migrations
{
    [DbContext(typeof(SyncDbContext))]
    partial class SyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("HwSync.Persistence.Sqlite.Entities.AcknowledgedFileEntity", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClientId", "FolderId", "RelativePath");

                    b.ToTable("acknowledged_files", (string)null);
                });

            modelBuilder.Entity("HwSync.Persistence.Sqlite.Entities.AcknowledgedStateEntity", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderId")
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId", "FolderId");

                    b.ToTable("acknowledged_states", (string)null);
                });

            modelBuilder.Entity("HwSync.Persistence.Sqlite.Entities.DeletionEventEntity", b =>
                {
                    b.Property<long>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DeletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginParticipantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PreviousModifiedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PreviousSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Number");

                    b.HasIndex("FolderId", "Number");

                    b.ToTable("deletion_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_deletion_size", "PreviousSize >= 0");
                        });
                });

            modelBuilder.Entity("HwSync.Persistence.Sqlite.Entities.FileSnapshotEntity", b =>
                {
                    b.Property<string>("FolderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<long>("ModifiedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("FolderId", "RelativePath");

                    b.ToTable("file_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_snapshot_size", "Size >= 0");
                        });
                });

            modelBuilder.Entity("HwSync.Persistence.Sqlite.Entities.FolderEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("RootPath")
                        .IsUnique();

                    b.ToTable("folders", (string)null);
                });

            modelBuilder.Entity("HwSync.Persistence.Sqlite.Entities.ParticipantEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParticipantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId")
                        .IsUnique();

                    b.ToTable("participant", null, t =>
                        {
                            t.HasCheckConstraint("ck_participant_singleton", "Id = 1");
                        });
                });

            modelBuilder.Entity("HwSync.Persistence.Sqlite.Entities.AcknowledgedFileEntity", b =>
                {
                    b.HasOne("HwSync.Persistence.Sqlite.Entities.AcknowledgedStateEntity", null)
                        .WithMany("Files")
                        .HasForeignKey("ClientId", "FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HwSync.Persistence.Sqlite.Entities.DeletionEventEntity", b =>
                {
                    b.HasOne("HwSync.Persistence.Sqlite.Entities.FolderEntity", null)
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HwSync.Persistence.Sqlite.Entities.FileSnapshotEntity", b =>
                {
                    b.HasOne("HwSync.Persistence.Sqlite.Entities.FolderEntity", null)
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HwSync.Persistence.Sqlite.Entities.AcknowledgedStateEntity", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
