<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../HwSync.Windows.Contract/HwSync.Windows.Contract.csproj" />
    <ProjectReference Include="../HwSync.Api.Client/HwSync.Api.Client.csproj" />
    <ProjectReference Include="../HwSync.Infrastructure/HwSync.Infrastructure.csproj" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
  </ItemGroup>
</Project>
