<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../HwSync.Windows.Contract/HwSync.Windows.Contract.csproj" />
    <ProjectReference Include="../HwSync.Windows.AppServices/HwSync.Windows.AppServices.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="sync-profiles.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../HwSync.Persistence.Sqlite.Migrations/HwSync.Persistence.Sqlite.Migrations.csproj" />
  </ItemGroup>
</Project>
